# Generated by Django 6.1.1 on 2026-09-22 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='назва кафедри')),
                ('head', models.CharField(max_length=255, verbose_name='завідувач кафедри')),
                ('description', models.TextField(blank=True, verbose_name='опис кафедри')),
            ],
            options={
                'verbose_name': 'кафедра',
                'verbose_name_plural': 'кафедри',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='назва факультету')),
                ('intro', models.TextField(verbose_name='короткий опис факультету')),
                ('about', models.TextField(verbose_name='основна інформація про факультет')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='адреса')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='сайт')),
            ],
            options={
                'verbose_name': 'текст головної сторінки',
                'verbose_name_plural': 'текст головної сторінки',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='назва спеціальності')),
                ('code', models.CharField(max_length=20, verbose_name='код спеціальності')),
                ('description', models.TextField(verbose_name='опис спеціальності')),
                ('coordinator_name', models.CharField(max_length=255, verbose_name="ім'я координатора набору")),
                ('coordinator_contact', models.CharField(max_length=255, verbose_name='контакт координатора набору')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='proga.department', verbose_name='випускова кафедра')),
            ],
            options={
                'verbose_name': 'спеціальність',
                'verbose_name_plural': 'спеціальності',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='назва дисципліни')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='proga.program', verbose_name='спеціальність')),
            ],
            options={
                'verbose_name': 'дисципліна',
                'verbose_name_plural': 'дисципліни',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="ім'я")),
                ('position', models.CharField(max_length=255, verbose_name='посада')),
                ('degree', models.CharField(blank=True, max_length=255, verbose_name='науковий ступінь')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='proga.department', verbose_name='кафедра')),
            ],
            options={
                'verbose_name': 'викладач',
                'verbose_name_plural': 'викладачі',
                'ordering': ['name'],
            },
        ),
    ]
