# Generated by Django 6.1.1 on 2026-10-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proga', '0010_rename_places_count_to_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeprogram',
            name='country',
            field=models.CharField(max_length=100, verbose_name='країна'),
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='places',
            field=models.PositiveIntegerField(verbose_name='кількість місць'),
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='university_name',
            field=models.CharField(max_length=255, verbose_name='назва університету'),
        ),
    ]
